/*
 *
 * ChatPage constants
 *
 */

export const DEFAULT_ACTION = 'app/ChatPage/DEFAULT_ACTION';

export const FETCH_USER = 'app/ChatPage/FETCH_USER';

export const CHANGE_TAB = 'app/ChatPage/CHANGE_TAB';

export const LOAD_SEARCH_FILTER = 'LOAD_SEARCH_FILTER';

export const FETCH_MESSAGE_USERS = 'FETCH_MESSAGE_USERS';
export const LOAD_MESSAGE_USERS = 'LOAD_MESSAGE_USERS';
export const LOAD_MESSAGE_USER = 'LOAD_MESSAGE_USER';

export const FETCH_MESSAGE_LIST = 'FETCH_MESSAGE_LIST';
export const LOAD_MESSAGE_LIST = 'LOAD_MESSAGE_LIST';
export const LOAD_MESSAGE_LIST_NEXTKEY = 'LOAD_MESSAGE_LIST_NEXTKEY';
export const LOAD_CLEAR_MESSAGE_CONTENT = 'LOAD_CLEAR_MESSAGE_CONTENT';

export const FETCH_TOUCH_USER = 'FETCH_TOUCH_USER';
export const LOAD_TOUCH_USER = 'LOAD_TOUCH_USER';

export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';
export const LOAD_CHAT_MESSAGE = 'LOAD_CHAT_MESSAGE';

export const DO_AGREE_EXCHANGE_TEL = 'DO_AGREE_EXCHANGE_TEL';
export const DO_DISAGREE_EXCHANGE_TEL = 'DO_DISAGREE_EXCHANGE_TEL';

export const DO_AGREE_INTERVIEW = 'DO_AGREE_INTERVIEW';
export const DO_DISAGREE_INTERVIEW = 'DO_DISAGREE_INTERVIEW';

export const FETCH_MESSAGE_GROUPS = 'FETCH_MESSAGE_GROUPS';
export const LOAD_MESSAGE_GROUPS = 'LOAD_MESSAGE_GROUPS';
export const LOAD_MESSAGE_GROUP = 'LOAD_MESSAGE_GROUP';

export const FETCH_GROUP_MESSAGE_LIST = 'FETCH_GROUP_MESSAGE_LIST';
export const LOAD_GROUP_MESSAGE_LIST = 'LOAD_GROUP_MESSAGE_LIST';
export const LOAD_GROUP_MESSAGE_LIST_NEXTKEY = 'LOAD_GROUP_MESSAGE_LIST_NEXTKEY';

export const LOAD_TOUCH_GROUP = 'LOAD_TOUCH_GROUP';

export const SEND_CHAT_GROUP_MESSAGE = 'SEND_CHAT_GROUP_MESSAGE';
export const LOAD_CHAT_GROUP_MESSAGE = 'LOAD_CHAT_GROUP_MESSAGE';

export const LOAD_GROUP_LIST = 'LOAD_GROUP_LIST';

export const FETCH_USER_CONTACTS = 'FETCH_USER_CONTACTS';
export const LOAD_USER_CONTACTS = 'LOAD_USER_CONTACTS';
export const LOAD_USER_CONTACT = 'LOAD_USER_CONTACT';

export const FETCH_USER_GROUPS = 'FETCH_USER_GROUPS';
export const LOAD_USER_GROUPS = 'LOAD_USER_GROUPS';
export const LOAD_USER_GROUP = 'LOAD_USER_GROUP';

export const LOAD_LOADING_STATUS = 'LOAD_LOADING_STATUS';
