/*
 *
 * ChatPage constants
 *
 */

export const DEFAULT_ACTION = 'app/ChatPage/DEFAULT_ACTION';

export const FETCH_USER = 'app/ChatPage/FETCH_USER';

export const CHANGE_TAB = 'app/ChatPage/CHANGE_TAB';

export const FETCH_MESSAGE_USERS = 'FETCH_MESSAGE_USERS';
export const LOAD_MESSAGE_USERS = 'LOAD_MESSAGE_USERS';

export const FETCH_MESSAGE_LIST = 'FETCH_MESSAGE_LIST';
export const LOAD_MESSAGE_LIST = 'LOAD_MESSAGE_LIST';
export const LOAD_MESSAGE_LIST_NEXTKEY = 'LOAD_MESSAGE_LIST_NEXTKEY';
export const LOAD_CLEAR_MESSAGE_CONTENT = 'LOAD_CLEAR_MESSAGE_CONTENT';

export const FETCH_TOUCH_USER = 'FETCH_TOUCH_USER';
export const LOAD_TOUCH_USER = 'LOAD_TOUCH_USER';

export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';
export const LOAD_CHAT_MESSAGE = 'LOAD_CHAT_MESSAGE';
